apiVersion: v1
kind: Pod
metadata:
  name: example-Pod
spec:
  hostNetwork: true
  automountServiceAccountToken: false
  securityContext:
    # When the Pod starts, it runs with user ID 3042
    runAsUser: 3042 
    # When the Pod starts, it runs with group id 4042
    runAsGroup: 4042
    # Any files are written with id 5042
    fsGroup: 5042
    # Any volumes are changed from root ownership
    # to the above ids
    fsGroupChangePolicy: "OnRootMismatch"
  volumes:
  - name: sc-vol
    emptyDir: {}
  containers:
    - name: sc-container
      image: my-container
      resources:
        requests:
          memory: "42Mi"
          cpu: "42m"
        ephemeral-storage: "1Gi"
          limits:
          memory: "128Mi"
        cpu: "84m"
          ephemeral-storage: "2Gi"
      volumeMounts:
      - name: sc-vol
        mountPath: /data/foo
  serviceAccountName: network-sa
